# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hi-brain/libhi_convert

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hi-brain/libhi_convert

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hi-brain/libhi_convert/CMakeFiles /home/hi-brain/libhi_convert/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hi-brain/libhi_convert/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hi_convert

# Build rule for target.
hi_convert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hi_convert
.PHONY : hi_convert

# fast build rule for target.
hi_convert/fast:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/build
.PHONY : hi_convert/fast

src/hi_convert.o: src/hi_convert.cpp.o
.PHONY : src/hi_convert.o

# target to build an object file
src/hi_convert.cpp.o:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_convert.cpp.o
.PHONY : src/hi_convert.cpp.o

src/hi_convert.i: src/hi_convert.cpp.i
.PHONY : src/hi_convert.i

# target to preprocess a source file
src/hi_convert.cpp.i:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_convert.cpp.i
.PHONY : src/hi_convert.cpp.i

src/hi_convert.s: src/hi_convert.cpp.s
.PHONY : src/hi_convert.s

# target to generate assembly for a file
src/hi_convert.cpp.s:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_convert.cpp.s
.PHONY : src/hi_convert.cpp.s

src/hi_matviewer.o: src/hi_matviewer.cpp.o
.PHONY : src/hi_matviewer.o

# target to build an object file
src/hi_matviewer.cpp.o:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer.cpp.o
.PHONY : src/hi_matviewer.cpp.o

src/hi_matviewer.i: src/hi_matviewer.cpp.i
.PHONY : src/hi_matviewer.i

# target to preprocess a source file
src/hi_matviewer.cpp.i:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer.cpp.i
.PHONY : src/hi_matviewer.cpp.i

src/hi_matviewer.s: src/hi_matviewer.cpp.s
.PHONY : src/hi_matviewer.s

# target to generate assembly for a file
src/hi_matviewer.cpp.s:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer.cpp.s
.PHONY : src/hi_matviewer.cpp.s

src/hi_matviewer3d.o: src/hi_matviewer3d.cpp.o
.PHONY : src/hi_matviewer3d.o

# target to build an object file
src/hi_matviewer3d.cpp.o:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer3d.cpp.o
.PHONY : src/hi_matviewer3d.cpp.o

src/hi_matviewer3d.i: src/hi_matviewer3d.cpp.i
.PHONY : src/hi_matviewer3d.i

# target to preprocess a source file
src/hi_matviewer3d.cpp.i:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer3d.cpp.i
.PHONY : src/hi_matviewer3d.cpp.i

src/hi_matviewer3d.s: src/hi_matviewer3d.cpp.s
.PHONY : src/hi_matviewer3d.s

# target to generate assembly for a file
src/hi_matviewer3d.cpp.s:
	$(MAKE) -f CMakeFiles/hi_convert.dir/build.make CMakeFiles/hi_convert.dir/src/hi_matviewer3d.cpp.s
.PHONY : src/hi_matviewer3d.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hi_convert"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/hi_convert.o"
	@echo "... src/hi_convert.i"
	@echo "... src/hi_convert.s"
	@echo "... src/hi_matviewer.o"
	@echo "... src/hi_matviewer.i"
	@echo "... src/hi_matviewer.s"
	@echo "... src/hi_matviewer3d.o"
	@echo "... src/hi_matviewer3d.i"
	@echo "... src/hi_matviewer3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

