// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "hi-brain.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
Vision::Time::operator>>= (cdrStream &_n) const
{
  sec >>= _n;
  msec >>= _n;

}

void
Vision::Time::operator<<= (cdrStream &_n)
{
  (::CORBA::ULong&)sec <<= _n;
  (::CORBA::ULong&)msec <<= _n;

}

void
Vision::Matrix::operator>>= (cdrStream &_n) const
{
  (const Time&) tm >>= _n;
  type >>= _n;
  (const _CORBA_Unbounded_Sequence_String&) name >>= _n;
  (const _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Short, 2, 2 > &) div >>= _n;
  (const _CORBA_Unbounded_Sequence_Octet&) pixels >>= _n;

}

void
Vision::Matrix::operator<<= (cdrStream &_n)
{
  (Time&)tm <<= _n;
  (::CORBA::UShort&)type <<= _n;
  (_CORBA_Unbounded_Sequence_String&)name <<= _n;
  (_CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Short, 2, 2 > &)div <<= _n;
  (_CORBA_Unbounded_Sequence_Octet&)pixels <<= _n;

}

void
Vision::Matarr::operator>>= (cdrStream &_n) const
{
  (const _CORBA_Unbounded_Sequence< Matrix > &) arr >>= _n;

}

void
Vision::Matarr::operator<<= (cdrStream &_n)
{
  (_CORBA_Unbounded_Sequence< Matrix > &)arr <<= _n;

}

